### ISSUE TITLE
Full support for ISO 8601 with milliseconds (WMS time dimension)

### ISSUE THREAD

**Issue by gastoneb** [ECCC-MSC/geomet-data-registry#26]
Hi, 

I'm using the [leaflet.timeDimension](https://github.com/socib/Leaflet.TimeDimension) plugin to make WMS requests of RADAR precip data from geomet. An issue I've found is with the plugin formatting the ISO8601 datestring with milliseconds, even though the value of milliseconds are always zero. E.g. `&time=2019-07-23T11:50:00.000Z`. The problem is that (at least for the layer I'm testing) geomet does not accept that `2019-07-23T11:50:00.000Z` is a valid time, instead only accepting values with no milliseconds, e.g. `2019-07-23T11:50:00Z`. I'll find a workaround in the meantime by modifying the plugin code, but I'm wondering if your service can be configured to fully implement the ISO8601 standard, including milliseconds, and make equivalence checks that can handle varying amounts of precision provided. E.g. `2019-01-01T00Z == 2019-01-01T00:00Z == 2019-01-01T00:00:00Z ==2019-01-01T00:00:00.000Z`

Thanks, and apologies if this Issue is opened on the wrong repo.

**Comment by RousseauLambertLP** [comment]
Hi @gastoneb 

First, thanks for your interest in our services and reporting this issue :)

We are already aware of this limitation. We basically don't support any other time format then `YYYY-MM-DDTHH:MM:SSZ`

At the moment we are working and developing an improved GeoMet (thus the geomet-data-registry repo) in which this feature should be supported, or at least give more flexibility to the user when requesting particular forecast hour and/or model run.

We also know that at the moment, a "wrong" time request might end up giving a error 500 to the user, this will be fixed in our next geomet release.

Given this issue is for the current GeoMet 2, I would say this is not the right repo to report errors, but there are no GitHub repository for GeoMet 2...

To report errors, you can use or email adress: ec.dps-client.ec@canada.ca and I would suggest that you subscribe to our [mailing list](https://lists.ec.gc.ca/cgi-bin/mailman/listinfo/geomet-info) (if not already done) to be aware of the upcoming changes to GeoMet.

Thanks

LP

**Comment by gastoneb** [comment]
Hi @RousseauLambertLP, thanks for the update. Please also pass on my thanks to the GeoMet team for providing this great service. 

I found a few other people who had encountered similar issues as me using leaflet.TimeDimension. There are some clues here, for anyone that stumbles upon this thread:
- https://gis.stackexchange.com/questions/321908/leaflet-time-series
- https://github.com/socib/Leaflet.TimeDimension/issues/168

The main workaround was to modify the `wmsParams.time` variable in leaflet.timedimension.layer.wms to follow the `YYYY-MM-DDTHH:MM:SSZ` format.
