### ISSUE TITLE
Add error logger for incomplete count in store

### ISSUE THREAD

**Issue by RousseauLambertLP** [ECCC-MSC/geomet-data-registry#57]
in `layer/base.py` we should add a error logger for when a file is added in a new model run and the previous model run did not get the total required number of files.

This way we could know if we missed a layer from the amqp feed.

**Comment by Dukestep** [comment]
Some sort of GeoHealthCheck plugin similar to VDF that we currently have for Geomet-Weather could be useful here too. Since we'll be relying heavily on AMQP notifications, knowing when we missed a notification would be extremely useful.

@tomkralidis, would using GeoHealthCheck be the move or would we like to bake in some sort of notification system directly into geomet-data-registry?

**Comment by tomkralidis** [comment]
+1 to emit a logger warning and then have something else analyze given logs for warnings, which could be a GHC plugin.

**Comment by RousseauLambertLP** [comment]
logger is integrated in GDR (#59). I will open another issue in our GHC repo for adding a plugin to monitor the ERRORs in GDR log file.
